version: '{branch}-{build}'

platform:
  - x86
  - x64

environment:
  global:
    PYTHONPATH: "C:\\testdir"
    PYTHONWARNINGS: "ignore:::wheel.pep425tags:"
    CONDA_BLD_VERSION: "3.5"
    CONDA_BLD: "C:\\conda"
    NUNIT: "nunit-console"

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.3"
    - PYTHON_VERSION: "3.4"
    - PYTHON_VERSION: "3.5"
    - PYTHON_VERSION: "3.6"

init:
  # Prepare environment
  - mkdir C:\testdir

  # Set environment variables depending based on build cfg
  - SET CONDA_PY=%PYTHON_VERSION:.=%
  - SET CONDA_BLD_ARCH=%PLATFORM:x=%
  - SET PYTHON=C:\PYTHON%CONDA_PY%
  - IF %PLATFORM%==x86 (SET CONDA_BLD_ARCH=32)
  - IF %PLATFORM%==x86 (SET NUNIT=%NUNIT%-x86)
  - IF %PLATFORM%==x64 (SET PYTHON=%PYTHON%-x64)

install:
  # install conda and deps
  - ps: .\ci\install_miniconda.ps1

  # install for wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install six"

build_script:
  # build clean sdist & wheel
  - "%PYTHON%\\python.exe setup.py sdist bdist_wheel"

  # build and dist conda package
  - cmd: "%CMD_IN_ENV% %CONDA_BLD%\\Scripts\\conda build conda.recipe"
  - ps: $CONDA_PKG=(& "$env:CONDA_BLD\\Scripts\\conda" build conda.recipe --output -q)
  - ps: copy-item $CONDA_PKG "$env:APPVEYOR_BUILD_FOLDER\\dist\\"

test_script:
  - ps: '& "$env:PYTHON\\Scripts\\pip.exe" install --no-cache-dir --force-reinstall --ignore-installed ("dist\\" + (gci dist\*.whl)[0].Name)'
  - ps: copy-item (gci -path build -re -include Python.Test.dll)[0].FullName C:\testdir
  - "%PYTHON%\\python.exe src\\tests\\runtests.py"
  # - "%NUNIT% src/embed_tests/bin/%PLATFORM%/ReleaseWin/Python.EmbeddingTest.dll"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
